In [379]:
# importing all the libraries required here
import pandas as pd
#import matplotlib.pyplot as plt
import numpy as np

In [380]:
# reading the dataset
datasetNames = ['ID number', 'Diagnosis', 
                'Mean Radius', 'Mean Texture', 'Mean Perimeter', 'Mean Area', 'Mean Smoothness', 'Mean Compactness', 'Mean Concavity', 'Mean Concave Points', 'Mean Symmetry', 'Mean Fractal Dimension',
                'SE Radius', 'SE Texture', 'SE Perimeter', 'SE Area', 'SE Smoothness', 'SE Compactness', 'SE Concavity', 'SE Concave Points', 'SE Symmetry', 'SE Fractal Dimension',
                'Worst Radius', 'Worst Texture', 'Worst Perimeter', 'Worst Area', 'Worst Smoothness', 'Worst Compactness', 'Worst Concavity', 'Worst Concave Points', 'Worst Symmetry', 'Worst Fractal Dimension']
dataset = pd.read_csv('data/wdbc.data', names = datasetNames, sep = ',')
dataset.head()

,ID number,Diagnosis,Mean Radius,Mean Texture,Mean Perimeter,Mean Area,Mean Smoothness,Mean Compactness,Mean Concavity,Mean Concave Points,...,Worst Radius,Worst Texture,Worst Perimeter,Worst Area,Worst Smoothness,Worst Compactness,Worst Concavity,Worst Concave Points,Worst Symmetry,Worst Fractal Dimension
0,842302,M,17.99,10.38,122.80,1001.0,0.11840,0.27760,0.3001,0.14710,...,25.38,17.33,184.60,2019.0,0.1622,0.6656,0.7119,0.2654,0.4601,0.11890
1,842517,M,20.57,17.77,132.90,1326.0,0.08474,0.07864,0.0869,0.07017,...,24.99,23.41,158.80,1956.0,0.1238,0.1866,0.2416,0.1860,0.2750,0.08902
2,84300903,M,19.69,21.25,130.00,1203.0,0.10960,0.15990,0.1974,0.12790,...,23.57,25.53,152.50,1709.0,0.1444,0.4245,0.4504,0.2430,0.3613,0.08758
3,84348301,M,11.42,20.38,77.58,386.1,0.14250,0.28390,0.2414,0.10520,...,14.91,26.50,98.87,567.7,0.2098,0.8663,0.6869,0.2575,0.6638,0.17300
4,84358402,M,20.29,14.34,135.10,1297.0,0.10030,0.13280,0.1980,0.10430,...,22.54,16.67,152.20,1575.0,0.1374,0.2050,0.4000,0.1625,0.2364,0.07678

In [381]:
dataset = dataset.drop(columns=['ID number'])
m , n = dataset.shape  # m = no. of samples, n = no. of features + target class
dataset = dataset.T #each column now represents a training set
dataset.head()

,0,1,2,3,4,5,6,7,8,9,...,559,560,561,562,563,564,565,566,567,568
Diagnosis,M,M,M,M,M,M,M,M,M,M,...,B,B,B,M,M,M,M,M,M,B
Mean Radius,17.99,20.57,19.69,11.42,20.29,12.45,18.25,13.71,13.0,12.46,...,11.51,14.05,11.2,15.22,20.92,21.56,20.13,16.6,20.6,7.76
Mean Texture,10.38,17.77,21.25,20.38,14.34,15.7,19.98,20.83,21.82,24.04,...,23.93,27.15,29.37,30.62,25.09,22.39,28.25,28.08,29.33,24.54
Mean Perimeter,122.8,132.9,130.0,77.58,135.1,82.57,119.6,90.2,87.5,83.97,...,74.52,91.38,70.67,103.4,143.0,142.0,131.2,108.3,140.1,47.92
Mean Area,1001.0,1326.0,1203.0,386.1,1297.0,477.1,1040.0,577.9,519.8,475.9,...,403.5,600.4,386.0,716.9,1347.0,1479.0,1261.0,858.1,1265.0,181.0

In [382]:
# seperate target class from dataset

Y_train = dataset.iloc[0]
X_train = dataset.iloc[1:n]

print(Y_train)
print(X_train)

0      M
1      M
2      M
3      M
4      M
      ..
564    M
565    M
566    M
567    M
568    B
Name: Diagnosis, Length: 569, dtype: object
                              0         1         2         3         4    \
Mean Radius                 17.99     20.57     19.69     11.42     20.29
Mean Texture                10.38     17.77     21.25     20.38     14.34
Mean Perimeter              122.8     132.9     130.0     77.58     135.1
Mean Area                  1001.0    1326.0    1203.0     386.1    1297.0
Mean Smoothness            0.1184   0.08474    0.1096    0.1425    0.1003
Mean Compactness           0.2776   0.07864    0.1599    0.2839    0.1328
Mean Concavity             0.3001    0.0869    0.1974    0.2414     0.198
Mean Concave Points        0.1471   0.07017    0.1279    0.1052    0.1043
Mean Symmetry              0.2419    0.1812    0.2069    0.2597    0.1809
Mean Fractal Dimension    0.07871   0.05667   0.05999   0.09744   0.05883
SE Radius                   1.095    0.5435    0.7456    0.4956    0.7572
SE Texture                 0.9053    0.7339    0.7869     1.156    0.7813
SE Perimeter                8.589     3.398     4.585     3.445     5.438
SE Area                     153.4     74.08     94.03     27.23     94.44
SE Smoothness            0.006399  0.005225   0.00615   0.00911   0.01149
SE Compactness            0.04904   0.01308   0.04006   0.07458   0.02461
SE Concavity              0.05373    0.0186   0.03832   0.05661   0.05688
SE Concave Points         0.01587    0.0134   0.02058   0.01867   0.01885
SE Symmetry               0.03003   0.01389    0.0225   0.05963   0.01756
SE Fractal Dimension     0.006193  0.003532  0.004571  0.009208  0.005115
Worst Radius                25.38     24.99     23.57     14.91     22.54
Worst Texture               17.33     23.41     25.53      26.5     16.67
Worst Perimeter             184.6     158.8     152.5     98.87     152.2
Worst Area                 2019.0    1956.0    1709.0     567.7    1575.0
Worst Smoothness           0.1622    0.1238    0.1444    0.2098    0.1374
Worst Compactness          0.6656    0.1866    0.4245    0.8663     0.205
Worst Concavity            0.7119    0.2416    0.4504    0.6869       0.4
Worst Concave Points       0.2654     0.186     0.243    0.2575    0.1625
Worst Symmetry             0.4601     0.275    0.3613    0.6638    0.2364
Worst Fractal Dimension    0.1189   0.08902   0.08758     0.173   0.07678

                              5         6         7         8         9    \
Mean Radius                 12.45     18.25     13.71      13.0     12.46
Mean Texture                 15.7     19.98     20.83     21.82     24.04
Mean Perimeter              82.57     119.6      90.2      87.5     83.97
Mean Area                   477.1    1040.0     577.9     519.8     475.9
Mean Smoothness            0.1278   0.09463    0.1189    0.1273    0.1186
Mean Compactness             0.17     0.109    0.1645    0.1932    0.2396
Mean Concavity             0.1578    0.1127   0.09366    0.1859    0.2273
Mean Concave Points       0.08089     0.074   0.05985   0.09353   0.08543
Mean Symmetry              0.2087    0.1794    0.2196     0.235     0.203
Mean Fractal Dimension    0.07613   0.05742   0.07451   0.07389   0.08243
SE Radius                  0.3345    0.4467    0.5835    0.3063    0.2976
SE Texture                 0.8902    0.7732     1.377     1.002     1.599
SE Perimeter                2.217      3.18     3.856     2.406     2.039
SE Area                     27.19     53.91     50.96     24.32     23.94
SE Smoothness             0.00751  0.004314  0.008805  0.005731  0.007149
SE Compactness            0.03345   0.01382   0.03029   0.03502   0.07217
SE Concavity              0.03672   0.02254   0.02488   0.03553   0.07743
SE Concave Points         0.01137   0.01039   0.01448   0.01226   0.01432
SE Symmetry               0.02165   0.01369   0.01486   0.02143   0.01789
SE Fractal Dimension     0.005082  0.002179  0.005412  0.003749   0.01008
Worst Radius                15.47     22.88     17.06     15.49     15.09
Worst Texture               23.75     27.66     28.14     30.73     40.68
Worst Perimeter             103.4     153.2     110.6     106.2     97.65
Worst Area                  741.6    1606.0     897.0     739.3     711.4
Worst Smoothness           0.1791    0.1442    0.1654    0.1703    0.1853
Worst Compactness          0.5249    0.2576    0.3682    0.5401     1.058
Worst Concavity            0.5355    0.3784    0.2678     0.539     1.105
Worst Concave Points       0.1741    0.1932    0.1556     0.206     0.221
Worst Symmetry             0.3985    0.3063    0.3196    0.4378    0.4366
Worst Fractal Dimension    0.1244   0.08368    0.1151    0.1072    0.2075

                         ...       559       560       561       562  \
Mean Radius              ...     11.51     14.05      11.2     15.22
Mean Texture             ...     23.93     27.15     29.37     30.62
Mean Perimeter           ...     74.52     91.38     70.67     103.4
Mean Area                ...     403.5     600.4     386.0     716.9
Mean Smoothness          ...   0.09261   0.09929   0.07449    0.1048
Mean Compactness         ...    0.1021    0.1126   0.03558    0.2087
Mean Concavity           ...    0.1112   0.04462       0.0     0.255
Mean Concave Points      ...   0.04105   0.04304       0.0   0.09429
Mean Symmetry            ...    0.1388    0.1537     0.106    0.2128
Mean Fractal Dimension   ...    0.0657   0.06171   0.05502   0.07152
SE Radius                ...    0.2388    0.3645    0.3141    0.2602
SE Texture               ...     2.904     1.492     3.896     1.205
SE Perimeter             ...     1.936     2.888     2.041     2.362
SE Area                  ...     16.97     29.84     22.81     22.65
SE Smoothness            ...    0.0082  0.007256  0.007594  0.004625
SE Compactness           ...   0.02982   0.02678  0.008878   0.04844
SE Concavity             ...   0.05738   0.02071       0.0   0.07359
SE Concave Points        ...   0.01267   0.01626       0.0   0.01608
SE Symmetry              ...   0.01488    0.0208   0.01989   0.02137
SE Fractal Dimension     ...  0.004738  0.005304  0.001773  0.006142
Worst Radius             ...     12.48      15.3     11.92     17.52
Worst Texture            ...     37.16     33.17      38.3     42.79
Worst Perimeter          ...     82.28     100.2     75.19     128.7
Worst Area               ...     474.2     706.7     439.6     915.0
Worst Smoothness         ...    0.1298    0.1241   0.09267    0.1417
Worst Compactness        ...    0.2517    0.2264   0.05494    0.7917
Worst Concavity          ...     0.363    0.1326       0.0      1.17
Worst Concave Points     ...   0.09653    0.1048       0.0    0.2356
Worst Symmetry           ...    0.2112     0.225    0.1566    0.4089
Worst Fractal Dimension  ...   0.08732   0.08321   0.05905    0.1409

                              563       564       565       566       567  \
Mean Radius                 20.92     21.56     20.13      16.6      20.6
Mean Texture                25.09     22.39     28.25     28.08     29.33
Mean Perimeter              143.0     142.0     131.2     108.3     140.1
Mean Area                  1347.0    1479.0    1261.0     858.1    1265.0
Mean Smoothness            0.1099     0.111    0.0978   0.08455    0.1178
Mean Compactness           0.2236    0.1159    0.1034    0.1023     0.277
Mean Concavity             0.3174    0.2439     0.144   0.09251    0.3514
Mean Concave Points        0.1474    0.1389   0.09791   0.05302     0.152
Mean Symmetry              0.2149    0.1726    0.1752     0.159    0.2397
Mean Fractal Dimension    0.06879   0.05623   0.05533   0.05648   0.07016
SE Radius                  0.9622     1.176    0.7655    0.4564     0.726
SE Texture                  1.026     1.256     2.463     1.075     1.595
SE Perimeter                8.758     7.673     5.203     3.425     5.772
SE Area                     118.8     158.7     99.04     48.55     86.22
SE Smoothness            0.006399    0.0103  0.005769  0.005903  0.006522
SE Compactness             0.0431   0.02891   0.02423   0.03731   0.06158
SE Concavity              0.07845   0.05198    0.0395    0.0473   0.07117
SE Concave Points         0.02624   0.02454   0.01678   0.01557   0.01664
SE Symmetry               0.02057   0.01114   0.01898   0.01318   0.02324
SE Fractal Dimension     0.006213  0.004239  0.002498  0.003892  0.006185
Worst Radius                24.29     25.45     23.69     18.98     25.74
Worst Texture               29.41      26.4     38.25     34.12     39.42
Worst Perimeter             179.1     166.1     155.0     126.7     184.6
Worst Area                 1819.0    2027.0    1731.0    1124.0    1821.0
Worst Smoothness           0.1407     0.141    0.1166    0.1139     0.165
Worst Compactness          0.4186    0.2113    0.1922    0.3094    0.8681
Worst Concavity            0.6599    0.4107    0.3215    0.3403    0.9387
Worst Concave Points       0.2542    0.2216    0.1628    0.1418     0.265
Worst Symmetry             0.2929     0.206    0.2572    0.2218    0.4087
Worst Fractal Dimension   0.09873   0.07115   0.06637    0.0782     0.124

                              568
Mean Radius                  7.76
Mean Texture                24.54
Mean Perimeter              47.92
Mean Area                   181.0
Mean Smoothness           0.05263
Mean Compactness          0.04362
Mean Concavity                0.0
Mean Concave Points           0.0
Mean Symmetry              0.1587
Mean Fractal Dimension    0.05884
SE Radius                  0.3857
SE Texture                  1.428
SE Perimeter                2.548
SE Area                     19.15
SE Smoothness            0.007189
SE Compactness            0.00466
SE Concavity                  0.0
SE Concave Points             0.0
SE Symmetry               0.02676
SE Fractal Dimension     0.002783
Worst Radius                9.456
Worst Texture               30.37
Worst Perimeter             59.16
Worst Area                  268.6
Worst Smoothness          0.08996
Worst Compactness         0.06444
Worst Concavity               0.0
Worst Concave Points          0.0
Worst Symmetry             0.2871
Worst Fractal Dimension   0.07039

[30 rows x 569 columns]

In [383]:
# Initialise ANN
import ANN
import layer
"""REMOVE BEFORE SUBMISSION"""
import importlib
importlib.reload(ANN)
importlib.reload(layer)


# initialise with learning rate, choice of loss funciton, input vector, output vector
ann = ANN.ANN(0.1,0,X_train,Y_train)
activations = [1,2,3,3] # 0-tanh, 1-relu, 2-sigmoid - activations of each non-output layer
ann.setLayers(activations, 7, 5, 3, 2) # variable arguments represent the number of nodes in each non-input layer 


print("Training Network")
ann.train()

i = 0
for l in ann.layers:
    print("\nProperties of layer", i, ":")
    l.get_properties()
    i += 1

the activations are [1, 2, 3, 3]
the variable argument is  (7, 5, 3, 2)
number of hidden layers 3

adding input layer
added 1 hidden layer
added 1 hidden layer
added 1 hidden layer
added 1 output layer
Training Network
propogating forward
propogating forward
propogating forward
propogating forward

Properties of layer 0 :
Number of nodes: 30
Activation Function: <function tanh at 0x0000024143F26E60>
Weights: [[-0.4280565   0.12252078 -0.08286492 -0.17388695  0.41078458  0.19184497
  -0.32091855  0.18935436 -0.0461589  -0.47157436  0.39133171 -0.07640429
  -0.14113233 -0.28590325 -0.19604913 -0.12937784 -0.28417543  0.0520482
  -0.45711733  0.09281962  0.34362067  0.35360467  0.37720663 -0.40135
  -0.00803037 -0.15927522 -0.23812925 -0.30421755 -0.13957436 -0.07745129]
 [-0.17036094 -0.07692619 -0.2238976  -0.19338883  0.43503691 -0.31952127
  -0.12267939  0.07300494 -0.42141069  0.34122865 -0.18039885  0.40008914
   0.19378692  0.2113207  -0.22876418 -0.28868641 -0.44627376  0.40889165
  -0.46095833 -0.14116911  0.38334098 -0.15178624  0.44927711  0.25872771
  -0.32314424  0.31100074  0.24358427 -0.18139391 -0.3727277  -0.29396111]
 [-0.2865941   0.40483904 -0.03565739 -0.48682216  0.19496208 -0.33585453
  -0.32236638 -0.23687449 -0.19203288  0.25702654  0.31170179  0.28640796
  -0.13435513 -0.30894069 -0.45116159  0.40642109 -0.27986984 -0.08831769
  -0.15403201 -0.21480928  0.48880357 -0.47662693  0.47925914 -0.10220728
   0.06187942 -0.11345417  0.4449021  -0.13982953 -0.37014606 -0.23816423]
 [ 0.16657854 -0.39961374  0.16190598 -0.40493023 -0.1417219  -0.06533308
  -0.44520768 -0.31689674  0.34581315  0.17174072 -0.27137024 -0.369957
  -0.13242015 -0.09271953 -0.08865274  0.00082351  0.26489217  0.47699702
   0.39129261 -0.47222402  0.47807418  0.05038616  0.37596125 -0.114257
   0.23034248 -0.01610943 -0.30619383  0.1010703  -0.04149819 -0.10698367]
 [ 0.17306431  0.09973503 -0.0096308   0.49056321  0.47963634 -0.23913257
   0.17102768 -0.25261043 -0.41459619 -0.24644617 -0.36967154 -0.17680011
   0.02077585 -0.36597128 -0.03387969  0.41141648 -0.34435593 -0.07341836
  -0.1071     -0.17796736 -0.22938791 -0.34145813 -0.09648307 -0.3672021
  -0.37606438  0.38652277  0.34908133  0.06001639 -0.01719116  0.03503215]
 [ 0.4210525  -0.34696427  0.24703676 -0.22317727 -0.17726378  0.1131539
   0.00859988 -0.26906607  0.21091754 -0.16615119  0.33661895  0.04495605
  -0.17431415  0.22804394  0.04694661  0.02673897 -0.01474682 -0.05292592
  -0.17520076 -0.1504164   0.39888849  0.20391931  0.13916174  0.16517184
  -0.34516111 -0.40005894 -0.17495825 -0.22881443 -0.38024486 -0.27134092]
 [ 0.34478045  0.05029098  0.38935692 -0.18403996  0.37370586  0.36576811
   0.03613986  0.04858027 -0.18757536  0.20955163  0.31395342  0.26530631
  -0.16539582  0.30115346  0.24473405 -0.21395273  0.43622475  0.14342101
  -0.17228656 -0.24191452  0.24433859  0.17798822 -0.437441   -0.43147845
   0.37359966  0.26030516  0.12655498  0.20915224 -0.01509293 -0.28178485]]
Bias: [[-0.07117198]
 [ 0.31327682]
 [-0.09960912]
 [ 0.42493208]
 [ 0.43993418]
 [ 0.11345412]
 [-0.31866744]]
Input vector:                               0         1         2         3         4    \
Mean Radius                 17.99     20.57     19.69     11.42     20.29
Mean Texture                10.38     17.77     21.25     20.38     14.34
Mean Perimeter              122.8     132.9     130.0     77.58     135.1
Mean Area                  1001.0    1326.0    1203.0     386.1    1297.0
Mean Smoothness            0.1184   0.08474    0.1096    0.1425    0.1003
Mean Compactness           0.2776   0.07864    0.1599    0.2839    0.1328
Mean Concavity             0.3001    0.0869    0.1974    0.2414     0.198
Mean Concave Points        0.1471   0.07017    0.1279    0.1052    0.1043
Mean Symmetry              0.2419    0.1812    0.2069    0.2597    0.1809
Mean Fractal Dimension    0.07871   0.05667   0.05999   0.09744   0.05883
SE Radius                   1.095    0.5435    0.7456    0.4956    0.7572
SE Texture                 0.9053    0.7339    0.7869     1.156    0.7813
SE Perimeter                8.589     3.398     4.585     3.445     5.438
SE Area                     153.4     74.08     94.03     27.23     94.44
SE Smoothness            0.006399  0.005225   0.00615   0.00911   0.01149
SE Compactness            0.04904   0.01308   0.04006   0.07458   0.02461
SE Concavity              0.05373    0.0186   0.03832   0.05661   0.05688
SE Concave Points         0.01587    0.0134   0.02058   0.01867   0.01885
SE Symmetry               0.03003   0.01389    0.0225   0.05963   0.01756
SE Fractal Dimension     0.006193  0.003532  0.004571  0.009208  0.005115
Worst Radius                25.38     24.99     23.57     14.91     22.54
Worst Texture               17.33     23.41     25.53      26.5     16.67
Worst Perimeter             184.6     158.8     152.5     98.87     152.2
Worst Area                 2019.0    1956.0    1709.0     567.7    1575.0
Worst Smoothness           0.1622    0.1238    0.1444    0.2098    0.1374
Worst Compactness          0.6656    0.1866    0.4245    0.8663     0.205
Worst Concavity            0.7119    0.2416    0.4504    0.6869       0.4
Worst Concave Points       0.2654     0.186     0.243    0.2575    0.1625
Worst Symmetry             0.4601     0.275    0.3613    0.6638    0.2364
Worst Fractal Dimension    0.1189   0.08902   0.08758     0.173   0.07678

                              5         6         7         8         9    \
Mean Radius                 12.45     18.25     13.71      13.0     12.46
Mean Texture                 15.7     19.98     20.83     21.82     24.04
Mean Perimeter              82.57     119.6      90.2      87.5     83.97
Mean Area                   477.1    1040.0     577.9     519.8     475.9
Mean Smoothness            0.1278   0.09463    0.1189    0.1273    0.1186
Mean Compactness             0.17     0.109    0.1645    0.1932    0.2396
Mean Concavity             0.1578    0.1127   0.09366    0.1859    0.2273
Mean Concave Points       0.08089     0.074   0.05985   0.09353   0.08543
Mean Symmetry              0.2087    0.1794    0.2196     0.235     0.203
Mean Fractal Dimension    0.07613   0.05742   0.07451   0.07389   0.08243
SE Radius                  0.3345    0.4467    0.5835    0.3063    0.2976
SE Texture                 0.8902    0.7732     1.377     1.002     1.599
SE Perimeter                2.217      3.18     3.856     2.406     2.039
SE Area                     27.19     53.91     50.96     24.32     23.94
SE Smoothness             0.00751  0.004314  0.008805  0.005731  0.007149
SE Compactness            0.03345   0.01382   0.03029   0.03502   0.07217
SE Concavity              0.03672   0.02254   0.02488   0.03553   0.07743
SE Concave Points         0.01137   0.01039   0.01448   0.01226   0.01432
SE Symmetry               0.02165   0.01369   0.01486   0.02143   0.01789
SE Fractal Dimension     0.005082  0.002179  0.005412  0.003749   0.01008
Worst Radius                15.47     22.88     17.06     15.49     15.09
Worst Texture               23.75     27.66     28.14     30.73     40.68
Worst Perimeter             103.4     153.2     110.6     106.2     97.65
Worst Area                  741.6    1606.0     897.0     739.3     711.4
Worst Smoothness           0.1791    0.1442    0.1654    0.1703    0.1853
Worst Compactness          0.5249    0.2576    0.3682    0.5401     1.058
Worst Concavity            0.5355    0.3784    0.2678     0.539     1.105
Worst Concave Points       0.1741    0.1932    0.1556     0.206     0.221
Worst Symmetry             0.3985    0.3063    0.3196    0.4378    0.4366
Worst Fractal Dimension    0.1244   0.08368    0.1151    0.1072    0.2075

                         ...       559       560       561       562  \
Mean Radius              ...     11.51     14.05      11.2     15.22
Mean Texture             ...     23.93     27.15     29.37     30.62
Mean Perimeter           ...     74.52     91.38     70.67     103.4
Mean Area                ...     403.5     600.4     386.0     716.9
Mean Smoothness          ...   0.09261   0.09929   0.07449    0.1048
Mean Compactness         ...    0.1021    0.1126   0.03558    0.2087
Mean Concavity           ...    0.1112   0.04462       0.0     0.255
Mean Concave Points      ...   0.04105   0.04304       0.0   0.09429
Mean Symmetry            ...    0.1388    0.1537     0.106    0.2128
Mean Fractal Dimension   ...    0.0657   0.06171   0.05502   0.07152
SE Radius                ...    0.2388    0.3645    0.3141    0.2602
SE Texture               ...     2.904     1.492     3.896     1.205
SE Perimeter             ...     1.936     2.888     2.041     2.362
SE Area                  ...     16.97     29.84     22.81     22.65
SE Smoothness            ...    0.0082  0.007256  0.007594  0.004625
SE Compactness           ...   0.02982   0.02678  0.008878   0.04844
SE Concavity             ...   0.05738   0.02071       0.0   0.07359
SE Concave Points        ...   0.01267   0.01626       0.0   0.01608
SE Symmetry              ...   0.01488    0.0208   0.01989   0.02137
SE Fractal Dimension     ...  0.004738  0.005304  0.001773  0.006142
Worst Radius             ...     12.48      15.3     11.92     17.52
Worst Texture            ...     37.16     33.17      38.3     42.79
Worst Perimeter          ...     82.28     100.2     75.19     128.7
Worst Area               ...     474.2     706.7     439.6     915.0
Worst Smoothness         ...    0.1298    0.1241   0.09267    0.1417
Worst Compactness        ...    0.2517    0.2264   0.05494    0.7917
Worst Concavity          ...     0.363    0.1326       0.0      1.17
Worst Concave Points     ...   0.09653    0.1048       0.0    0.2356
Worst Symmetry           ...    0.2112     0.225    0.1566    0.4089
Worst Fractal Dimension  ...   0.08732   0.08321   0.05905    0.1409

                              563       564       565       566       567  \
Mean Radius                 20.92     21.56     20.13      16.6      20.6
Mean Texture                25.09     22.39     28.25     28.08     29.33
Mean Perimeter              143.0     142.0     131.2     108.3     140.1
Mean Area                  1347.0    1479.0    1261.0     858.1    1265.0
Mean Smoothness            0.1099     0.111    0.0978   0.08455    0.1178
Mean Compactness           0.2236    0.1159    0.1034    0.1023     0.277
Mean Concavity             0.3174    0.2439     0.144   0.09251    0.3514
Mean Concave Points        0.1474    0.1389   0.09791   0.05302     0.152
Mean Symmetry              0.2149    0.1726    0.1752     0.159    0.2397
Mean Fractal Dimension    0.06879   0.05623   0.05533   0.05648   0.07016
SE Radius                  0.9622     1.176    0.7655    0.4564     0.726
SE Texture                  1.026     1.256     2.463     1.075     1.595
SE Perimeter                8.758     7.673     5.203     3.425     5.772
SE Area                     118.8     158.7     99.04     48.55     86.22
SE Smoothness            0.006399    0.0103  0.005769  0.005903  0.006522
SE Compactness             0.0431   0.02891   0.02423   0.03731   0.06158
SE Concavity              0.07845   0.05198    0.0395    0.0473   0.07117
SE Concave Points         0.02624   0.02454   0.01678   0.01557   0.01664
SE Symmetry               0.02057   0.01114   0.01898   0.01318   0.02324
SE Fractal Dimension     0.006213  0.004239  0.002498  0.003892  0.006185
Worst Radius                24.29     25.45     23.69     18.98     25.74
Worst Texture               29.41      26.4     38.25     34.12     39.42
Worst Perimeter             179.1     166.1     155.0     126.7     184.6
Worst Area                 1819.0    2027.0    1731.0    1124.0    1821.0
Worst Smoothness           0.1407     0.141    0.1166    0.1139     0.165
Worst Compactness          0.4186    0.2113    0.1922    0.3094    0.8681
Worst Concavity            0.6599    0.4107    0.3215    0.3403    0.9387
Worst Concave Points       0.2542    0.2216    0.1628    0.1418     0.265
Worst Symmetry             0.2929     0.206    0.2572    0.2218    0.4087
Worst Fractal Dimension   0.09873   0.07115   0.06637    0.0782     0.124

                              568
Mean Radius                  7.76
Mean Texture                24.54
Mean Perimeter              47.92
Mean Area                   181.0
Mean Smoothness           0.05263
Mean Compactness          0.04362
Mean Concavity                0.0
Mean Concave Points           0.0
Mean Symmetry              0.1587
Mean Fractal Dimension    0.05884
SE Radius                  0.3857
SE Texture                  1.428
SE Perimeter                2.548
SE Area                     19.15
SE Smoothness            0.007189
SE Compactness            0.00466
SE Concavity                  0.0
SE Concave Points             0.0
SE Symmetry               0.02676
SE Fractal Dimension     0.002783
Worst Radius                9.456
Worst Texture               30.37
Worst Perimeter             59.16
Worst Area                  268.6
Worst Smoothness          0.08996
Worst Compactness         0.06444
Worst Concavity               0.0
Worst Concave Points          0.0
Worst Symmetry             0.2871
Worst Fractal Dimension   0.07039

[30 rows x 569 columns]
Output vector: [[-1. -1. -1. ... -1. -1. -1.]
 [ 1.  1.  1. ...  1.  1.  1.]
 [-1. -1. -1. ... -1. -1. -1.]
 ...
 [-1. -1. -1. ... -1. -1. -1.]
 [ 1.  1.  1. ...  1.  1.  1.]
 [-1. -1. -1. ... -1. -1. -1.]]

Properties of layer 1 :
Number of nodes: 7
Activation Function: <function relu at 0x0000024144196950>
Weights: [[ 0.21637952 -0.14346308 -0.09836141  0.4446024  -0.25437966  0.04761267
   0.49639268]
 [ 0.00557996  0.15644894 -0.43548345 -0.47992622  0.36547977 -0.39961625
   0.0785747 ]
 [-0.01055348  0.07794357 -0.32562915  0.35721955 -0.10833081 -0.01954911
   0.22086842]
 [ 0.09848868 -0.17029539  0.04320727 -0.44079262  0.21254855  0.27681234
  -0.29259658]
 [-0.26563543  0.04861791  0.49254841  0.08131086 -0.2590068   0.09381558
  -0.28040701]]
Bias: [[ 0.18291727]
 [-0.22923573]
 [ 0.18505082]
 [ 0.41797467]
 [-0.08110546]]
Input vector: [[-1. -1. -1. ... -1. -1. -1.]
 [ 1.  1.  1. ...  1.  1.  1.]
 [-1. -1. -1. ... -1. -1. -1.]
 ...
 [-1. -1. -1. ... -1. -1. -1.]
 [ 1.  1.  1. ...  1.  1.  1.]
 [-1. -1. -1. ... -1. -1. -1.]]
Output vector: [[0.         0.         0.         ... 0.         0.         0.        ]
 [0.         0.         0.         ... 0.         0.         0.        ]
 [0.10987076 0.10987076 0.10987076 ... 0.10987076 0.10987076 0.10987076]
 [0.90363634 0.90363634 0.90363634 ... 0.90363634 0.90363634 0.90363634]
 [0.29251802 0.29251802 0.29251802 ... 0.29251802 0.29251802 0.29251802]]

Properties of layer 2 :
Number of nodes: 5
Activation Function: <function sigmoid at 0x00000241453E1120>
Weights: [[-0.32121869 -0.19676018 -0.48797927  0.47831335 -0.39789548]
 [ 0.08740184 -0.37799376 -0.00270136  0.44748687  0.15426151]
 [ 0.30341721 -0.26144548 -0.10976256  0.08780854 -0.37147377]]
Bias: [[-0.2174208 ]
 [-0.01101151]
 [-0.04426451]]
Input vector: [[0.         0.         0.         ... 0.         0.         0.        ]
 [0.         0.         0.         ... 0.         0.         0.        ]
 [0.10987076 0.10987076 0.10987076 ... 0.10987076 0.10987076 0.10987076]
 [0.90363634 0.90363634 0.90363634 ... 0.90363634 0.90363634 0.90363634]
 [0.29251802 0.29251802 0.29251802 ... 0.29251802 0.29251802 0.29251802]]
Output vector: [[0.5111967  0.5111967  0.5111967  ... 0.5111967  0.5111967  0.5111967 ]
 [0.6078256  0.6078256  0.6078256  ... 0.6078256  0.6078256  0.6078256 ]
 [0.47860307 0.47860307 0.47860307 ... 0.47860307 0.47860307 0.47860307]]

Properties of layer 3 :
Number of nodes: 3
Activation Function: <function sigmoid at 0x00000241453E1120>
Weights: [[ 0.20252378  0.03481202  0.19539855]
 [-0.19561294  0.42874758  0.20966414]]
Bias: [[ 0.44961014]
 [-0.22116363]]
Input vector: [[0.5111967  0.5111967  0.5111967  ... 0.5111967  0.5111967  0.5111967 ]
 [0.6078256  0.6078256  0.6078256  ... 0.6078256  0.6078256  0.6078256 ]
 [0.47860307 0.47860307 0.47860307 ... 0.47860307 0.47860307 0.47860307]]
Output vector: [[0.6610143  0.6610143  0.6610143  ... 0.6610143  0.6610143  0.6610143 ]
 [0.50994605 0.50994605 0.50994605 ... 0.50994605 0.50994605 0.50994605]]

Properties of layer 4 :
Number of nodes: 2
Activation Function: None
Weights: []
Bias: []
Input vector: [[0.6610143  0.6610143  0.6610143  ... 0.6610143  0.6610143  0.6610143 ]
 [0.50994605 0.50994605 0.50994605 ... 0.50994605 0.50994605 0.50994605]]
Output vector: None